// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_technician.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsTechnician {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTOaV_dzkRzl6BcvxhAz52qvCfg0gYXyw',
    appId: '1:183469206239:web:908de669db327a9f26976a',
    messagingSenderId: '183469206239',
    projectId: 'hammertechnician-f164c',
    authDomain: 'hammertechnician-f164c.firebaseapp.com',
    storageBucket: 'hammertechnician-f164c.firebasestorage.app',
    measurementId: 'G-Z7N2ZYRR1Z',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8rGzVZHJHFTSsmm2AcUD_cVfzjQ8qwtI',
    appId: '1:183469206239:ios:ed1d14f04469d3ec26976a',
    messagingSenderId: '183469206239',
    projectId: 'hammertechnician-f164c',
    storageBucket: 'hammertechnician-f164c.firebasestorage.app',
    iosBundleId: 'com.example.hammerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8rGzVZHJHFTSsmm2AcUD_cVfzjQ8qwtI',
    appId: '1:183469206239:ios:ed1d14f04469d3ec26976a',
    messagingSenderId: '183469206239',
    projectId: 'hammertechnician-f164c',
    storageBucket: 'hammertechnician-f164c.firebasestorage.app',
    iosBundleId: 'com.example.hammerApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyA6KKTnPBSKYM6QJUmQPKnm7ERDBAwDGdQ",
    appId: "1:183469206239:android:79cc6f4d91b0bed826976a",
    messagingSenderId: "183469206239",
    projectId: "hammertechnician-f164c",
    storageBucket: "hammertechnician-f164c.firebasestorage.app",
  );
}
